version: "3"
networks:
  default:
    external:
      name: app
services: 
  flink-ai-flow:
    image: ${BASE_IMAGE_FULL}
    container_name: flink-ai-flow
    volumes:
      - ..:/workspace:cached
      - ../../vendor/flink-ai-extended/flink-ai-flow:/workspace/flink-ai-flow:cached
    command: /bin/sh -c "while sleep 1000; do :; done"