version: "3"
networks:
  default:
    external:
      name: app
services: 
  flink-statefun:
    image: ${BASE_IMAGE_FULL}
    container_name: flink-statefun
    volumes:
      - ..:/workspace:cached
      - ../../vendor/flink-statefun:/workspace/flink-statefun:cached
    command: /bin/sh -c "while sleep 1000; do :; done"