version: "3"
networks:
  default:
    external:
      name: app
services: 
  alink:
    image: ${BASE_IMAGE_FULL}
    container_name: alink
    volumes:
      - ..:/workspace:cached
      - ../../vendor/alink:/workspace/alink:cached
    command: /bin/sh -c "while sleep 1000; do :; done"