version: "3"
networks:
  default:
    external:
      name: app
services: 
  flink-dl:
    image: ${BASE_IMAGE_FULL}
    container_name: flink-dl
    volumes:
      - ..:/workspace:cached
      - ../../vendor/flink-ai-extended/deep-learning-on-flink:/workspace/flink-dl:cached
    command: /bin/sh -c "while sleep 1000; do :; done"